import type { NextPage } from "next";
import Head from "next/head";
import Wallpaper from "../components/Wallpaper";

const Home: NextPage = () => {
  return (
    <div className="h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-slate-200">
        <Wallpaper />
      </main>
    </div>
  );
};

export default Home;
